# Generated by Django 5.2 on 2025-05-07 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatteryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('oem', models.CharField(max_length=100)),
                ('oem_part_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ComponentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=100)),
                ('machine_id', models.IntegerField()),
                ('model', models.CharField(max_length=100)),
                ('year_of_manufacture', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_document_link', models.FileField(blank=True, help_text='PDF or document describing battery replacement for this component', null=True, upload_to='procedures/')),
                ('battery_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maintenance.batterymodel')),
                ('component_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.componentmodel')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='maintenance.machine')),
            ],
        ),
        migrations.CreateModel(
            name='BatteryReplacementRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replacement_interval', models.CharField(max_length=100)),
                ('last_replaced', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('battery_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maintenance.batterymodel')),
                ('replaced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battery_replacements', to='maintenance.component')),
            ],
        ),
    ]
