# Generated by Django 5.2 on 2025-05-07 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatteryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('oem', models.CharField(max_length=100)),
                ('oem_part_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_model', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ComponentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('machine_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BatteryReplacementRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('last_replaced', models.DateField(blank=True, null=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.component')),
            ],
        ),
        migrations.AddField(
            model_name='component',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.machine'),
        ),
    ]
