# Generated by Django 5.2 on 2025-05-07 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='year_of_manufacture',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
