# Generated by Django 5.2 on 2025-05-10 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='battery',
            name='replacement_interval_months',
            field=models.PositiveIntegerField(blank=True, help_text='Number of months between replacements (if interval type is months)', null=True),
        ),
        migrations.AddField(
            model_name='battery',
            name='replacement_interval_type',
            field=models.CharField(choices=[('months', 'Months'), ('alarm', 'On Alarm')], default='months', max_length=10),
        ),
    ]
