# Generated by Django 5.2.1 on 2025-05-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_battery_replacement_interval_months_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='procedure_document',
            field=models.FileField(blank=True, help_text='Upload a document for the replacement procedure (optional).', null=True, upload_to='procedure_documents/'),
        ),
    ]
