version: "3.9"

services:
  web:
    build: .
    command: /bin/sh -c "python manage.py migrate && python manage.py collectstatic --noinput && python -m uvicorn battery_manager.asgi:application --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - staticfiles:/app/staticfiles
    working_dir: /app/battery_manager
    environment:
      - DEBUG=1

volumes:
  staticfiles: