version: "3.9"

services:
  web:
    build: .
    # The command is now taken from the Dockerfile's CMD (your entrypoint.sh)
    # command: /bin/sh -c "python manage.py migrate && python manage.py collectstatic --noinput && python -m uvicorn battery_manager.asgi:application --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - staticfiles:/app/staticfiles # For static files collected by collectstatic
      - db_data:/data              # For the SQLite database if moved as per previous discussions
    working_dir: /app/battery_manager
    environment:
      - DEBUG=1
      - SQLITE_PATH=/data/db.sqlite3 # Example if you moved the DB
      # Add other environment variables like SECRET_KEY here
      # - SECRET_KEY=your_actual_secret_key
    tty: true # Needed for the interactive prompt in entrypoint.sh (read command)
    stdin_open: true # Needed for the interactive prompt in entrypoint.sh (read command)


volumes:
  staticfiles:
  db_data: # For the SQLite database